name: Publish
on:
  push:
    tags:
      - v*
env:
  CRATE_NAME: treetrace
jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check version
        run: |
          version=`cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "${{ env.CRATE_NAME }}") | .version'`
          version=v"${version}"
          echo "Got '${version}' from Cargo.toml"
          [ "${version}" ] && [ "${version}" == "${{ github.ref_name }}" ]
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nixify
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        shell: bash
        run: nix flake check
  publish:
    name: Publish
    needs: [version, check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
